Repository DIGITAL-SOFT-PTY/virtual-keyboard-react-simple, pull requests merged in 2023-06, with the labels that each got.

#4 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, enhancement, good first issue, help wanted, Feeddback

#5 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, Feeddback

#8 Keyboard
  package.json
  src/keyboard.tsx
Labels: documentation

#10 Create SECURITY.md
  SECURITY.md
Labels: documentation

#11 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#12 Update issue templates
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/name-issue.md
Labels: documentation

#13 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#14 Create dependabot.yml
  .github/dependabot.yml
Labels: documentation

#20 Update keyboard.tsx
  src/keyboard.tsx
Labels: invalid

#21 Nota
  src/keyboard.tsx
Labels: Feedback

#22 Actualizar Branch
  .github/dependabot.yml
  .gitignore
  README.md
  package.json
  resources/teclado-virtual2.png
  src/keyboard.js
  src/keyboard.tsx
  virtual-keyboard-react-simple-1.0.11.tgz
  virtual-keyboard-react-simple-1.0.16.tgz
Labels: Feedback
